# Generated by Django 5.1.1 on 2024-09-18 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voteId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='voteId'),
        ),
    ]
