# Generated by Django 5.1.1 on 2024-09-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_voteid'),
    ]

    operations = [
    ]
